version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb-container
    ports:
      - 27018:27017
    volumes:
      - './mongodb:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-express-container
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

# docker-compose -f docker-compose up -d             // create container
#docker-compose -f mongo-compose.yml down            // roll back 
#mongosh "mongodb://root:example@localhost:27018" --username root --authenticationDatabase admin